export const UPDATE_LOGIN_STATUS = "UPDATE_LOGIN_STATUS";
export const UPDATE_USER = "UPDATE_USER";
export const USER_TOKEN = "USER_TOKEN";
export const TOTAL_OFF_CAMPUS_ROOMS_BOOKED = "TOTAL_OFF_CAMPUS_ROOMS_BOOKED";
export const TOTAL_ON_CAMPUS_ROOMS_BOOKED = "TOTAL_ON_CAMPUS_ROOMS_BOOKED";
